version: "3"
services:

  maria:
    restart: always
    image: mariadb:latest
    networks:
      - backend
    ports:
      - "33060:3306"
    environment:
    - MYSQL_DATABASE=tanksdb
    - MYSQL_USER=tanks-admin
    - MYSQL_PASSWORD=tanks-password
    - MYSQL_ROOT_PASSWORD=tanks-password

  api:
    restart: always

    build:
      context: ../

    networks:
      - backend
    ports:
      - "8080:8080"

    command: bash -c "sleep 15 && cd /server/target && /usr/bin/java -jar tanks-1.5.6.RELEASE.jar"


networks:
  backend:
