version: "3"
services:

  maria:
    restart: always
    image: mariadb:latest
    networks:
      - backend
    ports:
      - "33060:3306"
    environment:
    - MYSQL_DATABASE=tanksdb
    - MYSQL_USER=tanks-admin
    - MYSQL_PASSWORD=tanks-password
    - MYSQL_ROOT_PASSWORD=tanks-password

  api:
    restart: always

    build:
      context: ../

    networks:
      - backend
    ports:
      - "8080:8080"
    links:
      - maria

    command: bash -c "sleep 20 && /usr/bin/java -Djava.security.egd=file:/dev/./urandom -jar /server/target/tanks-1.5.6.RELEASE.jar"


networks:
  backend:
